config/routes.rb
Rails.application.routes.draw do
 
    
  get 'home/index'

    root 'home#index'
    
  

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  get '/auth/:provider/callback' => 'sessions#create'

  get '/signout' => 'sessions#destroy', :as => :signout

  get '/signin' => 'sessions#new', :as => :signin
    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    has_many :comments, as: :commentable
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :posts
    has_many :comments
    
    def self.create_with_omniauth(auth)
      create! do |user|
       user.provider = auth['provider']
       user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
       end
     end
    end
    
     def normalimage
       "http://graph.facebook.com/#{self.uid}/picture?type=normal"
     end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :user_signed_in?


 

private
    

    
  def user_signed_in?
     !!session[:user_id]
  end

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    
   
    def new
      @comment = Comment.new
    end

    def create
      @post =  Post.find_by_id(params[:post_id]) if params[:post_id]
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
      @comment = @commentable.comments.new(comments_params)
      @comment.user_id = current_user.id

      if @comment.save
        redirect_to :back, notice: 'Your comment was successfully posted!'
      else
        redirect_to :back, notice: "Your comment wasn't posted!"
      end
    end
    
      def edit
          @comment = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
          @comment = Post.find_by_id(params[:post_id]) if params[:post_id]
      end
    
  def update
       @comment = Post.find_by_id(params[:post_id]) if params[:post_id]
     
       @comment = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
       respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to post_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: post_path }
      else
        format.html { render post_path }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
    
    
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
        
    end

    private

    def comments_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type, :user_id )
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
    @comment = Comment.new
    @comments = Comment.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: posts_path }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
      redirect_to '/auth/facebook'
    end
    
   def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                    :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to posts_path, :notice => "Signed in!"
   end
    
    def destroy
      reset_session
      redirect_to root_url, notice => 'Signed out'
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
     <section class="comment-list">
         
           
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
             <%= image_tag(comment.user.normalimage) %>
                <figcaption class="text-center"><%= comment.user.name %></figcaption>
              </figure>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-repeat"></i>  <%= comment.user.name %> <strong>answered:</strong></div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i>  <%= time_ago_in_words(comment.created_at) %> ago</time>
                  </header>
                  <div class="comment-post">
                    <p>
                   <strong><%= comment.body %></strong>
                    </p>
                  </div>
                  
                    <% if current_user.name == comment.user.name %>
                 
                   
     
                   <%= link_to 'Destroy', comment, method: :delete %>
                   <% end %>
                </div>
              </div>
                
      <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Reply to this comment", class: "form-control", id: "comm" %><br/>
                <li><%= f.submit "Reply", class: "btn-danger", id: 'ttt' %></li>
      <br/>            
      <% end %>
            </div>
     
          </article>
     
     
            <ul>
               <%= render(partial: 'comments/comment', collection: comment.comments) %>
            </ul>
        </section>
        

app/views/comments/edit.html.erb
<div class="page-header" id="ceh">Edit your comment!</div>

<div class="container" >        
      <%= form_for [@comment, Comment.new] do |f| %>
      <%= f.text_area :body, class: "form-control" %><br/>
      <%= f.submit "Update", class: "btn-danger" %>
   
      <br/>            
      <% end %>
</div>

app/views/home/index.html.erb
<!-- tests -->

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">

<div class="container">
      
      <script id="metamorph-1-start" type="text/x-placeholder"></script><script id="metamorph-21-start" type="text/x-placeholder"></script>

	<div class="container text-center">
	    <form class="form-signin" data-ember-action="2">
	    	<h2 class="form-signin-heading">Sign in</h2>

			<strong id="bbb">Welcome to my test app!
                Facebook authentication is configured and working, posts page is available only for signed in users, before writing posts please login. In order to login, please push the button below: </strong>
			<br><br>

			
<p>
<a class="btn btn-primary social-login-btn social-facebook" href="/auth/facebook"><i class="fa fa-facebook"></i></a>

</p>


        </form>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="homee">

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <br/>
    <%= f.text_area :content, class: "form-control", rows: "6", placeholder: "Write your thoughts here"%><br/>
      <div class="container" id="share"><%= f.submit "Share your post with us!", class: "btn btn-danger btn-lg btn-block", id: "ttt" %></div>
  </div>
 
 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
<div class="nav" id='mph'><h3>Welcome <%= current_user.name %></h3>  
  
<%= image_tag(current_user.normalimage) %>
    
    <br/>
    <%= link_to "Sign out", signout_path, class: "btn btn-danger", id: 'ttt' %>
    <br/>
    <br/>
</div>
<br/>
<%= render 'form' %>

<br/>

 
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2 class="page-header" id="pst">Latest posts ...</h2>
        <% @posts.each do |post| %>
        <section class="comment-list">
          <!-- First Comment -->
           
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail" id="asd">
               
                   <%= image_tag(post.user.normalimage) %>

                <figcaption class="text-center"><%= post.user.name %></figcaption>
              </figure>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow left" id="postback">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i>  <%= post.user.name %> wrote:</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i>  <%= time_ago_in_words(post.created_at) %> ago</time>
                  </header>
                  <div class="comment-post">
                    <p>
                   <%= post.content %>
                    </p>
                  </div>
                  
                    <% if current_user.name == post.user.name %>
                 <%= link_to 'Edit', edit_post_path(post) %>
     
     
               <%= link_to 'Destroy', post, method: :delete %>
                   <% end %>
                </div>
              </div>
                <%= form_for [post, Comment.new] do |f| %>
                <%= f.text_area :body, placeholder: "Comment that post", class: "form-control" %><br/>
                <%= f.submit "Comment this!", class: "btn-success" %>
                <% end %>
                <br/>
            </div>
               
          </article>
            
            <ul>
                <%= render(partial: 'comments/comment', collection: post.comments) %>
            </ul>
            
        </section>
        
        
         <% end %>
        
      </div>
       
    </div>
   
    </div>
<% else %>

<h1>Please Signup before posting content!</h1>

<%= link_to "Proceed with signin in", home_index_path %>

<% end %>  

<!-- test there -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>